name: Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
    
  lint:
    uses: ./.github/workflows/lint.yml
    
  docs:
    uses: ./.github/workflows/build-docs.yml 